<option value="" disabled {{ old('prefecture', $user->prefecture) ? '' : 'selected' }}>Please select</option>
<option value="Hokkaido" {{ old('prefecture', $user->prefecture) === 'Hokkaido' ? 'selected' : '' }}>Hokkaido</option>
<option value="Aomori" {{ old('prefecture', $user->prefecture) === 'Aomori' ? 'selected' : '' }}>Aomori</option>
<option value="Iwate" {{ old('prefecture', $user->prefecture) === 'Iwate' ? 'selected' : '' }}>Iwate</option>
<option value="Miyagi" {{ old('prefecture', $user->prefecture) === 'Miyagi' ? 'selected' : '' }}>Miyagi</option>
<option value="Akita" {{ old('prefecture', $user->prefecture) === 'Akita' ? 'selected' : '' }}>Akita</option>
<option value="Yamagata" {{ old('prefecture', $user->prefecture) === 'Yamagata' ? 'selected' : '' }}>Yamagata</option>
<option value="Fukushima" {{ old('prefecture', $user->prefecture) === 'Fukushima' ? 'selected' : '' }}>Fukushima</option>
<option value="Ibaraki" {{ old('prefecture', $user->prefecture) === 'Ibaraki' ? 'selected' : '' }}>Ibaraki</option>
<option value="Tochigi" {{ old('prefecture', $user->prefecture) === 'Tochigi' ? 'selected' : '' }}>Tochigi</option>
<option value="Gunma" {{ old('prefecture', $user->prefecture) === 'Gunma' ? 'selected' : '' }}>Gunma</option>
<option value="Saitama" {{ old('prefecture', $user->prefecture) === 'Saitama' ? 'selected' : '' }}>Saitama</option>
<option value="Chiba" {{ old('prefecture', $user->prefecture) === 'Chiba' ? 'selected' : '' }}>Chiba</option>
<option value="Tokyo" {{ old('prefecture', $user->prefecture) === 'Tokyo' ? 'selected' : '' }}>Tokyo</option>
<option value="Kanagawa" {{ old('prefecture', $user->prefecture) === 'Kanagawa' ? 'selected' : '' }}>Kanagawa</option>
<option value="Niigata" {{ old('prefecture', $user->prefecture) === 'Niigata' ? 'selected' : '' }}>Niigata</option>
<option value="Toyama" {{ old('prefecture', $user->prefecture) === 'Toyama' ? 'selected' : '' }}>Toyama</option>
<option value="Ishikawa" {{ old('prefecture', $user->prefecture) === 'Ishikawa' ? 'selected' : '' }}>Ishikawa</option>
<option value="Fukui" {{ old('prefecture', $user->prefecture) === 'Fukui' ? 'selected' : '' }}>Fukui</option>
<option value="Yamanashi" {{ old('prefecture', $user->prefecture) === 'Yamanashi' ? 'selected' : '' }}>Yamanashi</option>
<option value="Nagano" {{ old('prefecture', $user->prefecture) === 'Nagano' ? 'selected' : '' }}>Nagano</option>
<option value="Gifu" {{ old('prefecture', $user->prefecture) === 'Gifu' ? 'selected' : '' }}>Gifu</option>
<option value="Shizuoka" {{ old('prefecture', $user->prefecture) === 'Shizuoka' ? 'selected' : '' }}>Shizuoka</option>
<option value="Aichi" {{ old('prefecture', $user->prefecture) === 'Aichi' ? 'selected' : '' }}>Aichi</option>
<option value="Mie" {{ old('prefecture', $user->prefecture) === 'Mie' ? 'selected' : '' }}>Mie</option>
<option value="Shiga" {{ old('prefecture', $user->prefecture) === 'Shiga' ? 'selected' : '' }}>Shiga</option>
<option value="Kyoto" {{ old('prefecture', $user->prefecture) === 'Kyoto' ? 'selected' : '' }}>Kyoto</option>
<option value="Osaka" {{ old('prefecture', $user->prefecture) === 'Osaka' ? 'selected' : '' }}>Osaka</option>
<option value="Hyogo" {{ old('prefecture', $user->prefecture) === 'Hyogo' ? 'selected' : '' }}>Hyogo</option>
<option value="Nara" {{ old('prefecture', $user->prefecture) === 'Nara' ? 'selected' : '' }}>Nara</option>
<option value="Wakayama" {{ old('prefecture', $user->prefecture) === 'Wakayama' ? 'selected' : '' }}>Wakayama</option>
<option value="Tottori" {{ old('prefecture', $user->prefecture) === 'Tottori' ? 'selected' : '' }}>Tottori</option>
<option value="Shimane" {{ old('prefecture', $user->prefecture) === 'Shimane' ? 'selected' : '' }}>Shimane</option>
<option value="Okayama" {{ old('prefecture', $user->prefecture) === 'Okayama' ? 'selected' : '' }}>Okayama</option>
<option value="Hiroshima" {{ old('prefecture', $user->prefecture) === 'Hiroshima' ? 'selected' : '' }}>Hiroshima</option>
<option value="Yamaguchi" {{ old('prefecture', $user->prefecture) === 'Yamaguchi' ? 'selected' : '' }}>Yamaguchi</option>
<option value="Tokushima" {{ old('prefecture', $user->prefecture) === 'Tokushima' ? 'selected' : '' }}>Tokushima</option>
<option value="Kagawa" {{ old('prefecture', $user->prefecture) === 'Kagawa' ? 'selected' : '' }}>Kagawa</option>
<option value="Ehime" {{ old('prefecture', $user->prefecture) === 'Ehime' ? 'selected' : '' }}>Ehime</option>
<option value="Kochi" {{ old('prefecture', $user->prefecture) === 'Kochi' ? 'selected' : '' }}>Kochi</option>
<option value="Fukuoka" {{ old('prefecture', $user->prefecture) === 'Fukuoka' ? 'selected' : '' }}>Fukuoka</option>
<option value="Saga" {{ old('prefecture', $user->prefecture) === 'Saga' ? 'selected' : '' }}>Saga</option>
<option value="Nagasaki" {{ old('prefecture', $user->prefecture) === 'Nagasaki' ? 'selected' : '' }}>Nagasaki</option>
<option value="Kumamoto" {{ old('prefecture', $user->prefecture) === 'Kumamoto' ? 'selected' : '' }}>Kumamoto</option>
<option value="Oita" {{ old('prefecture', $user->prefecture) === 'Oita' ? 'selected' : '' }}>Oita</option>
<option value="Miyazaki" {{ old('prefecture', $user->prefecture) === 'Miyazaki' ? 'selected' : '' }}>Miyazaki</option>
<option value="Kagoshima" {{ old('prefecture', $user->prefecture) === 'Kagoshima' ? 'selected' : '' }}>Kagoshima</option>
<option value="Okinawa" {{ old('prefecture', $user->prefecture) === 'Okinawa' ? 'selected' : '' }}>Okinawa</option>
<option value="Overseas" {{ old('prefecture', $user->prefecture) === 'Overseas' ? 'selected' : '' }}>Overseas</option>